# Generated by Django 5.2.8 on 2025-12-03 18:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='inventory_p_name_f6a6a1_idx'), models.Index(fields=['category', 'name'], name='inventory_p_categor_4cd409_idx')],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='inventory_s_name_b6074b_idx'), models.Index(fields=['city'], name='inventory_s_city_73e89e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('type', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out'), ('TRANSFER', 'Transfer')], db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('sourceStore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements_out', to='inventory.store')),
                ('targetStore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements_in', to='inventory.store')),
            ],
            options={
                'indexes': [models.Index(fields=['product', '-timestamp'], name='inventory_m_product_682418_idx'), models.Index(fields=['type', '-timestamp'], name='inventory_m_type_87331a_idx'), models.Index(fields=['sourceStore', 'targetStore'], name='inventory_m_sourceS_445220_idx')],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('minStock', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_inventory', to='inventory.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_inventory', to='inventory.store')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'store'], name='inventory_i_product_63a757_idx')],
                'unique_together': {('product', 'store')},
            },
        ),
    ]
